USE [H15_PROJET_E05]
GO

ALTER TABLE RDV.RDVs
ADD AgentID int NOT NULL DEFAULT 0


ALTER TABLE RDV.RDVs
	ADD CONSTRAINT FK_RDVs_Agents_AgentID
	FOREIGN KEY (AgentID) 
	REFERENCES Agent.Agents

CREATE INDEX index_photoProprietesRDVID
ON RDV.PhotoProprietes(RDVID)

CREATE INDEX index_StatutsRDVID
ON RDV.Statuts(RDVID)

CREATE INDEX index_AgentsAgentID
ON RDV.RDVs (AgentID)

CREATE INDEX index_RDVForfaitID
ON RDV.RDVs (ForfaitID)