//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace photo_hdr_duval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Emails = new HashSet<Email>();
        }
    
        public int AgentID { get; set; }
        public string NomPrenomAgent { get; set; }
        public string NomEntreprise { get; set; }
        public string Adresse { get; set; }
        public int TelPrincipal { get; set; }
        public int TelSecondaire { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
    }
}
