//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace photo_hdr_duval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.RDVs = new HashSet<RDV>();
        }
    
        public int AgentID { get; set; }
        public string NomAgent { get; set; }
        public string PrenomAgent { get; set; }
        public string NomEntreprise { get; set; }
        public string Adresse { get; set; }
        public string CodePostal { get; set; }
        public long TelPrincipal { get; set; }
        public Nullable<long> TelSecondaire { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
    
        public virtual ICollection<RDV> RDVs { get; set; }
    }
}
