//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace photo_hdr_duval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int FactureID { get; set; }
        public Nullable<int> CoutTotal { get; set; }
        public Nullable<int> Deplacement { get; set; }
        public Nullable<int> VisiteVirtuelle { get; set; }
        public byte[] AsVisiteVirtuelle { get; set; }
        public int RDVID { get; set; }
    
        public virtual RDV RDV { get; set; }
    }
}
